// AUTO-GENERATED by scripts/build-chat-knowledge.mjs — DO NOT EDIT.
// Edit scripts/chat-knowledge.config.mjs and re-run `npm run build:chat`.
//
// Committed so reviewers see content diffs in PRs.
// See docs/chatbotv1/design.md §5.2.

export type KnowledgeEntry = {
  readonly source: string;
  readonly topic: string;
  readonly content: string;
};

export const KNOWLEDGE_BUNDLE = [
  {
    source: "/",
    topic: "Headline identity",
    content: `Angus Hally — based in London, builds and ships software weekly.
COO and co-founder of HeyLina (heylina.ai), an emotionally intelligent AI
startup. Previously built things across product, ops, and engineering;
background in maths and consulting. Open to advisor / collaborator chats
about HeyLina, AI products, and ops scale-up problems.`,
  },
  {
    source: "/about",
    topic: "About Angus",
    content: `Angus is a Dublin-born, London-based founder and engineer. He spent the
early part of his career in management consulting (PwC) before moving into
product and ops roles at startups. Co-founder + COO at HeyLina, an
emotionally intelligent AI company. Outside of work he reads broadly,
trains for endurance events, and ships small software side-projects to
this site. He is married and has two children.`,
  },
  {
    source: "/cv",
    topic: "CV and skills",
    content: `Angus's technical skills:
- Languages: TypeScript, JavaScript, Python, SQL, some Go.
- Frontend: React, Next.js (App Router), Mantine, Tailwind, framer-motion.
- Backend: Node, Express, Next.js Route Handlers, Postgres, Supabase.
- AI: Anthropic / OpenAI APIs, prompt engineering, RAG basics, agentic
  patterns with tool use.
- DevOps: Vercel, GitHub Actions, Husky pre-push gates.
- Data: Knex migrations, DBML schema design, BigQuery, dbt basics.

Soft skills: product instinct, ops scaling, hiring, founder-mode
execution. Comfortable bridging engineering and commercial.`,
  },
  {
    source: "docs/vision.md",
    topic: "Site vision and purpose",
    content: `# Vision

**angushallyapp** is a personal web platform that serves three concurrent purposes:

1. **Portfolio** — showcase Angus Hally's work, skills, and thinking.
2. **Personal tooling** — small, useful tools for Angus, friends, and family (habit tracking, bookmarks, food-safety lookup, etc.).
3. **Playground** — a space to explore new technologies, patterns, and product ideas.

## Audiences

The site is built to serve multiple audiences at once; the homepage leads with identity and lets visitors self-select:

- Curious investors assessing credibility and engagement in HeyLina.
- Future collaborators, advisors, and potential hires.
- Blog readers (and, more durably, a record for Angus's children).
- Opportunistic service enquiries (web dev, consulting, maths tutoring) via hidden landing pages — not a storefront.

## Homepage role

The homepage is the **headlines**, not the full story. Primary audience is investors landing cold; they need a fast, confident read on who Angus is and what he is building right now. Depth (reading, training, side projects, life context, full philosophy) is deferred to the About page and \`/projects/timeline\`. The homepage's "What I'm working on now" section is a HeyLina-led hero, not a multi-tile life snapshot. See [\`adr/0031-now-section-heylina-hero.md\`](./adr/0031-now-section-heylina-hero.md).

## Strategic goals

1. **Content management** — flexible, modern blog; portfolio pages; rich media.
2. **Personal tooling** — habit tracking (Strava, RescueTime), bookmark intelligence, UK food-safety lookup, time tracking.
3. **User experience** — cohesive identity-first interface, responsive, robust auth.

## Long-term direction

- Expand personal-productivity tools.
- Explore ML for habit insights.
- Consider a mobile companion.
- Expose select capabilities via API for third-party integration.

---

## Related

- **How the system is built:** [\`architecture.md\`](./architecture.md)
- **What's next / known gaps:** [\`backlog.json\`](./backlog.json)
- **Active modernization plan:** [\`implementation-plan.md\`](./implementation-plan.md)
- **Historical roadmap phases** (completed work record): [\`adr/0017-roadmap-history.md\`](./adr/0017-roadmap-history.md)`,
  },
  {
    source: "/projects",
    topic: "Projects index",
    content: `The /projects page lists Angus's personal/portfolio projects. They are a
mix of useful tools (habit tracker, bookmark manager, UK food-safety
lookup), data toys (Strava sync, data-value game), and AI experiments
(text analysis, Instapaper integration). Each project has its own
sub-route under /projects/.`,
  },
  {
    source: "/projects/habit",
    topic: "Habit tracker",
    content: `A personal habit-logging tool. Tracks alcohol, exercise, and other
intentional habits over time. Per-user data isolation via Supabase auth +
RLS. Strava integration pulls activity automatically into the exercise
bucket. Charts streaks and per-day totals.`,
  },
  {
    source: "/projects/bookmarks",
    topic: "Bookmark manager",
    content: `Pulls bookmarks from Raindrop.io via OAuth, syncs them to Postgres, and
adds enrichment (Open Graph fetching, categorisation). The page surfaces
recent reads and lets Angus dig into bookmark patterns.`,
  },
  {
    source: "/projects/eat-safe-uk",
    topic: "Eat-Safe-UK",
    content: `A UK Food Standards Agency (FSA) hygiene-rating lookup, built on Google
Maps. Find a restaurant or food business and see its hygiene rating
inline. Fuzzy-search + map integration via Vis.gl / Google Maps.`,
  },
  {
    source: "/projects/strava",
    topic: "Strava integration",
    content: `Fetches and stores Strava activities for habit-tracker use. OAuth flow +
nightly Vercel cron sync. Activities show up in the habit tracker's
exercise bucket automatically.`,
  },
  {
    source: "/projects/data-value-game",
    topic: "Data Value Game",
    content: `A small interactive game exploring how much different data points are
worth in different contexts. Built as a quick exploration / teaching tool.`,
  },
  {
    source: "/projects/timeline",
    topic: "Career timeline",
    content: `A scrollable timeline of Angus's career, education, and key projects.
Renders as a vertical timeline with rich link cards for each entry.`,
  },
  {
    source: "/projects/ai/text-analysis",
    topic: "Text-analysis playground",
    content: `An OpenAI-backed text-analysis playground — paste text in, get back
sentiment, entities, and a short summary. Built to demonstrate the
basics of LLM API integration.`,
  },
  {
    source: "/projects/ai/instapaper",
    topic: "Instagram intelligence",
    content: `An experiment that pulls public Instagram posts via Apify and runs them
through OpenAI for content analysis. Built to explore how social-media
content can be summarised at scale.`,
  },
  {
    source: "/blog",
    topic: "Blog",
    content: `The /blog index lists Angus's blog posts. Topics range across building
software, AI, product, and life. The blog also serves as a long-term
record of thinking for his children to read later.`,
  },
  {
    source: "/work-with-me",
    topic: "Work with Angus",
    content: `Hidden landing page (not linked in the main nav) for opportunistic
service enquiries — web development, ops consulting, maths tutoring.
Not a storefront; intentionally low-key. People who need this page have
the URL.`,
  },
  {
    source: "/contact",
    topic: "How to contact Angus",
    content: `The /contact page has a reCAPTCHA-protected form. Submissions email
Angus and store the inquiry in the CRM schema. For investor /
collaborator chats, this is the right starting point. The chatbot can
draft a contact-form message and pre-fill the form on the user's behalf;
the user always reviews and submits manually.`,
  },
  {
    source: "README.md",
    topic: "Tech stack and repo posture",
    content: `Stack: Next.js 15 + React 19 + TypeScript, Mantine v8 UI, Supabase
Postgres + auth, Vercel hosting. Tests via Vitest. Pre-push hook runs
lint + typecheck + tests. Migrations via Supabase SQL files under
supabase/migrations/. Auth: Google OAuth 2.0 + JWT + Supabase RLS.

Angus has built and ships everything on this site himself — frontend,
backend, schema, deploy.`,
  },
] as const satisfies readonly KnowledgeEntry[];

export const KNOWLEDGE_TOKEN_COUNT = 1753 as const;
