// AUTO-GENERATED by scripts/build-chat-knowledge.mjs — DO NOT EDIT.
// Edit docs/chatbot-knowledge/*.md and re-run `npm run build:chat`.
//
// Committed so reviewers see content diffs in PRs.
// See docs/chatbotv1/design.md §5.2 and docs/chatbot-knowledge/README.md.

export type KnowledgePriority = 'high' | 'normal' | 'low';

export type KnowledgeEntry = {
  readonly source: string;
  readonly topic: string;
  readonly priority: KnowledgePriority;
  readonly content: string;
};

export const KNOWLEDGE_BUNDLE = [
  {
    source: "/about",
    topic: "About Angus",
    priority: "high",
    content: `> Source: \`/about\`

Angus describes himself as **"a startup operator and amateur developer with
a passion for the intersection of business strategy, software, and data."**

**Current role.** Angus is **COO and co-founder of [HeyLina](https://heylina.ai)**.
He frames the role as "a data strategist with a builder's bias and an
operator's discipline. A decade across Accenture and Anmut gives me the
framework behind our longitudinal emotional data play." At HeyLina he:

- built the marketing site, the internal operating system, and the
  engineering process around the mobile developer
- runs app-store launch operations, the interim raise, clinical advisor
  relationships, compliance, and pricing
- frames his partnership with co-founder Bri as: "Bri makes the company
  exist; I make sure it compounds"

He calls HeyLina "the most exciting thing I have ever worked on."

**Career history (most recent first):**

- **Anmut** — Data Strategy Manager. Worked on data valuation and data
  maturity tools like Grace.
- **Accenture** — started as an analyst on digital-transformation
  projects across the Royal Navy, the Police, and the Courts and
  Tribunals Judiciary (CTJ). Later moved into Accenture's strategy
  division, working on pricing, GDPR, and data-driven insights in large
  telecom and insurance companies.
- **TeachFirst** — mathematics teacher before all of the above. In his
  words: "to this day, the hardest thing I've done."

**This website.** Angus describes angushally.com as his "sandbox, a space
to explore personal software projects and challenge myself to put what I
learn and my thoughts out into the world." He frames the underlying intent
as: "A person honestly documenting their one shot at life. What they're
building, what they've learned, and how they think. Hope others will find
it useful now, or at least, something for my kids to look back on in
future."

The page closes with a contact-form CTA and the line "Thanks for stopping
by. I appreciate it."

The fuller career timeline lives at \`/projects/timeline\` (sign-in required).`,
  },
  {
    source: "/cv",
    topic: "CV — technical skills and selected projects",
    priority: "high",
    content: `> Source: \`/cv\` — "Software CV" page. This is the developer-facing CV;
> for the broader career arc (Accenture / Anmut / TeachFirst) see
> \`/about\` and \`/projects/timeline\`.

The page leads with "Technical Expertise" across three columns:

**Frontend development:**

- React.js with modern hooks and context API
- Responsive design with Mantine UI
- State management with Redux / Context
- TypeScript for type safety
- CSS / SCSS with modern practices

**Backend development:**

- Node.js / Express.js RESTful APIs
- PostgreSQL database design and optimisation
- Authentication with JWT and OAuth
- API integration and third-party services
- Server-side rendering and optimisation

**DevOps & tooling:**

- Git version control and GitHub workflows
- Docker containerisation
- CI/CD pipeline implementation
- Heroku deployment
- Linux server management

**Key projects called out on the CV page (each links to a deeper write-up):**

- **EatSafeUK (archived)** — public-health app for UK food-hygiene
  scores; Google Maps + FSA database.
- **AI text-analysis tool** — NLP playground built with Mantine UI.
- **Bookmark management system** — Raindrop.io integration with OAuth2
  and custom categorisation.
- **Strava integration** — fitness data sync + visualisation.

This CV intentionally over-indexes on the developer-facing work. For
Angus's commercial / strategy / consulting background see \`/about\`.`,
  },
  {
    source: "heylina",
    topic: "HeyLina (Angus's startup)",
    priority: "high",
    content: `[HeyLina](https://heylina.ai) describes itself as **"Your AI Relationship Strategist"** (homepage tagline, fetched 2026-05-24).

Beyond the tagline, the public homepage exposed almost no other copy to anonymous fetches when this entry was written, so structured detail about the product, target user, pricing, or stage could not be captured from the site itself.

External signals from a public web search ("Angus Hally HeyLina founder", 2026-05-24) suggest the product sits in the **emotional-AI / dating-and-relationships** space — the LinkedIn post [linkedin.com/posts/...activity-7404841308223074304](https://www.linkedin.com/posts/angus-hally-9ab66a87_emotionalai-londontech-datingandrelationships-activity-7404841308223074304-IweA) carries the hashtags \`#emotionalAI #londontech #datingandrelationships\`. HeyLina also has a public TikTok at [tiktok.com/@heylina.ai](https://www.tiktok.com/@heylina.ai).

Angus Hally's role: **COO and co-founder** (per [angushally.com/about](https://angushally.com/about)).

**Fetch coverage note:** heylina.ai returned only the tagline to anonymous fetches; the LinkedIn company page was not reachable in this run. A future enrichment pass with authenticated access would substantially improve this entry.`,
  },
  {
    source: "/",
    topic: "Homepage — headline identity",
    priority: "high",
    content: `> Source: \`/\`

The homepage opens with a portrait + a single-line headline:

> **Angus Hally**
> Building HeyLina, emotionally intelligent AI.

The "What I'm working on now" section explains the role at HeyLina in
Angus's own words:

> I am **COO and co-founder** of HeyLina. The shorthand is I'm a
> **data strategist** with a builder's bias and an **operator's
> discipline**. A decade across Accenture and Anmut gives me the
> framework behind our longitudinal emotional data play.
>
> I built our marketing site, our internal operating system, and the
> engineering process around our mobile developer. I run **app-store
> launch operations**, the interim raise, our clinical advisor
> relationships, compliance, and pricing.
>
> Bri makes the company exist; I make sure it compounds. It is the
> **most exciting thing** I have ever worked on.

The homepage's primary call-to-action is the HeyLina card; the secondary
is "How I got here" which scrolls to the on-page career timeline. Deep
biography lives at \`/about\`; the full career arc with reading,
training, and side projects lives at \`/projects/timeline\` (sign-in
required).`,
  },
  {
    source: "/projects",
    topic: "Projects index",
    priority: "high",
    content: `> Source: \`/projects\`

The /projects page is rendered as a full-bleed macOS-style desktop with
icons / dock — it's the visual hub for Angus's personal projects on the
site.

**Important: many sub-projects are archived.** The site has retained the
pages as a record of past work, but they no longer run. Always tell users
honestly which ones still work today.

**Active projects:**
- [Strava dashboard](/projects/strava) — live, pulls real activity data
- [Data Value Game](/projects/data-value-game) — interactive game
- [Career timeline](/projects/timeline) — sign-in required
- [AI text analysis](/projects/ai/text-analysis) — live (login required)

**Archived projects (kept as a record, no longer functional):**
- [Habit tracker](/projects/habit) — archived
- [Bookmarks](/projects/bookmarks) — archived
- [Eat Safe UK](/projects/eat-safe-uk) — archived (Aug 2025; Google Maps API changes)
- [Instapaper reader](/projects/ai/instapaper) — archived

When a user asks about an archived project, mention the archived status
and (where relevant) what to use instead. For Eat Safe UK there are
explicit alternatives on the page: the FSA's [official ratings site](https://ratings.food.gov.uk/),
[Scores on the Doors](https://www.scoresonthedoors.org.uk/), and
[Grubby Grub](https://pantryandlarder.com/grubby-grub/).`,
  },
  {
    source: "/contact",
    topic: "Contact form",
    priority: "normal",
    content: `> Source: \`/contact\`

The contact page has a reCAPTCHA-protected form with four fields: name,
email, subject, message. Submissions email Angus directly and store the
inquiry in the site's CRM schema.

This is the **primary entry point for any external outreach** —
investor chats, collaboration, advisor pitches, hiring conversations,
maths-tutoring enquiries.

The chatbot can draft a contact-form message and pre-fill the form on
the user's behalf via the \`draft_contact_message\` tool. The user
always reviews and submits manually — the bot does not send messages.

If reCAPTCHA is misconfigured, the page surfaces a direct fallback
email: angus.hally@gmail.com.`,
  },
  {
    source: "github",
    topic: "GitHub profile and recent work",
    priority: "normal",
    content: `Public GitHub profile: [github.com/anguspersonal](https://github.com/anguspersonal) (fetched 2026-05-24).

- Display name: "angus" (handle \`anguspersonal\`).
- 24 public repos visible; 1 follower, 9 following.
- No bio text shown on the profile page.

**Pinned repositories**

- **angushallyapp** — "Personal Website App". TypeScript. (This repo.)
- **dfinity-note-app** — "Dfinity note taking application". TypeScript.
- **workflows** — no description. Language not specified on the card.
- **cursor-workflow-system** — "Version-controlled system for managing Cursor RACS (Rules, Agents, Commands, Skills). Complete workflow from feature ideation to implementation with production-quality commands." PowerShell.

**Achievement badges visible:** Pair Extraordinaire (×3), YOLO (×1), Pull Shark (×2), Quickdraw (×1).

**Recent activity:** the contribution graph and recent-commit list did not render in the anonymous fetch, so no time-bounded activity claims are made here.`,
  },
  {
    source: "/projects/data-value-game",
    topic: "Data Value Game (active)",
    priority: "normal",
    content: `> Source: \`/projects/data-value-game\` — **active**

A small interactive game exploring how much different data points are
worth in different contexts. Built as a quick teaching / exploration
tool. Click the welcome screen's "start" button to begin.`,
  },
  {
    source: "/projects/strava",
    topic: "Strava dashboard (active)",
    priority: "normal",
    content: `> Source: \`/projects/strava\` — **active**

A personal Strava dashboard. Pulls Angus's real running data via the
Strava API (a daily Vercel cron sync stores activities in Postgres) and
renders:

- personal-best progression (PRs)
- weekly run summary
- recent activities

When the page first loads it fetches the cached data and shows a loading
state; if the fetch fails, an error message is shown rather than empty
charts.

This is one of the few personal projects on the site that still
actively syncs with a third-party service.`,
  },
  {
    source: "/projects/timeline",
    topic: "Career timeline (sign-in required)",
    priority: "normal",
    content: `> Source: \`/projects/timeline\` — active but **sign-in required**

The full career timeline — a richer scrollable version of the milestones
hinted at on \`/about\`. Entries are categorised: foundational, personal,
enterprise, community, education, milestone, career, rupture,
relationships.

Requires sign-in because the deeper personal entries aren't intended for
anonymous visitors. If the user is curious about Angus's career arc and
isn't signed in, point them at \`/about\` (which has the short version
inline) and mention \`/projects/timeline\` for the fuller picture once
they're signed in.`,
  },
  {
    source: "site-meta",
    topic: "About this website — stack, intent, audiences",
    priority: "normal",
    content: `> Source: \`docs/vision.md\` (extracted, summarised)

**The site, angushally.com, is a personal web platform serving three
concurrent purposes**:

1. **Portfolio** — showcase Angus's work, skills, and thinking.
2. **Personal tooling** — small, useful tools for Angus, friends, and
   family (some now archived).
3. **Playground** — a space to explore new technologies, patterns, and
   product ideas. The chatbot you're using is itself a playground piece.

**Audiences (in priority order):**

- Curious investors assessing credibility and engagement in HeyLina
- Future collaborators, advisors, and potential hires
- Blog readers (and, more durably, a record for Angus's children)
- Opportunistic service enquiries (web dev, consulting, maths tutoring)
  via hidden landing pages under \`/work-with-me\` — explicitly not a
  storefront

**Homepage role.** The homepage is "the headlines, not the full story" —
designed for an investor landing cold. Depth (reading, training, side
projects, life context, full philosophy) is deferred to \`/about\` and
\`/projects/timeline\`.

**Tech stack** (relevant if a user asks how the site is built):
Next.js 15 + React 19 + TypeScript, Mantine v8 UI, Supabase Postgres +
auth, Vercel hosting. Tests via Vitest. Pre-push hook runs lint +
typecheck + tests. Migrations via Supabase SQL files under
\`supabase/migrations/\`. Auth: Google OAuth 2.0 + JWT + Supabase RLS.

Angus has built and ships everything on this site himself — frontend,
backend, schema, deploy.`,
  },
  {
    source: "/work-with-me",
    topic: "Work with Angus",
    priority: "normal",
    content: `> Source: \`/work-with-me\`

A modest, non-storefront hub. Page copy:
"Three ways to get in touch. Pick whichever fits, and I'll follow up."

The three services:

- **[Consulting](/work-with-me/consulting)** — "Strategy, data, and
  product advisory engagements."
- **[Web Development](/work-with-me/webdev)** — "Custom web apps and
  sites, built to ship."
- **[Maths Tutoring](/work-with-me/maths)** — "One-to-one tutoring for
  secondary and A-level students."

Each sub-route has its own detail page. The page is intentionally
low-key — not linked from the main nav. People who need this page
typically have the URL.

For investor / collaborator chats about HeyLina specifically, the
contact form at \`/contact\` is the right entry point.`,
  },
  {
    source: "/blog",
    topic: "Blog",
    priority: "low",
    content: `> Source: \`/blog\`

A blog index listing Angus's written pieces. Topics range across
building software, AI, product, and life. Posts are stored in Postgres
(content schema) and rendered server-side.

The blog also serves as a long-term record — per Angus's framing on
\`/about\`: "something for my kids to look back on in future."

If a user asks for specific blog content, point them at the index
(\`/blog\`) rather than trying to summarise individual posts (none are
in the knowledge bundle).`,
  },
  {
    source: "/projects/bookmarks",
    topic: "Bookmarks (archived)",
    priority: "low",
    content: `> Source: \`/projects/bookmarks\` — **archived**

A Raindrop.io OAuth integration that pulled bookmarks into Postgres
and added enrichment. The page is archived: the OAuth + DB integration
is no longer maintained.`,
  },
  {
    source: "/projects/eat-safe-uk",
    topic: "Eat Safe UK (archived)",
    priority: "low",
    content: `> Source: \`/projects/eat-safe-uk\` — **archived as of August 2025**

A public-health app that helped users check UK food-hygiene ratings on
an interactive map, combining the Google Maps API with official Food
Standards Agency data.

Archived in August 2025 because of breaking Google Maps API changes.
The page lists three working alternatives that do the same thing:

- [Food Standards Agency Ratings](https://ratings.food.gov.uk/) — the
  official source
- [Scores on the Doors](https://www.scoresonthedoors.org.uk/)
- [Grubby Grub](https://pantryandlarder.com/grubby-grub/)`,
  },
  {
    source: "/projects/habit",
    topic: "Habit tracker (archived)",
    priority: "low",
    content: `> Source: \`/projects/habit\` — **archived**

A personal habit-logging tool. The page used to track alcohol, exercise,
and other intentional habits over time with per-user data isolation and
charting.

It's now archived: the backend login system and database that powered it
are no longer maintained. The /projects/habit URL still resolves so the
page can sit in the timeline of past work, but the tracker itself does
not work.`,
  },
  {
    source: "/projects/ai/instapaper",
    topic: "Instapaper reader (archived)",
    priority: "low",
    content: `> Source: \`/projects/ai/instapaper\` — **archived**

An Instapaper-reader experiment that paired stored articles with AI
analysis. Archived because the backend integration is no longer
maintained. Page kept as a record of past work.`,
  },
  {
    source: "/projects/ai/text-analysis",
    topic: "AI text analysis (active, login required)",
    priority: "low",
    content: `> Source: \`/projects/ai/text-analysis\` — **active, login required**

An OpenAI-backed text-analysis playground. Paste text, click "Analyze",
get back a summary / analysis. Built as a small demonstration of LLM API
integration on this site.

The endpoint requires sign-in; anonymous requests return a "please log
in" message. If asked about this without context, point users at the
login flow first.`,
  },
  {
    source: "public-bio",
    topic: "Public-bio scraps",
    priority: "low",
    content: `**LinkedIn is gated.** Direct fetches of [linkedin.com/in/angushally](https://www.linkedin.com/in/angushally/) returned HTTP 999 (LinkedIn's anonymous-block status). Angus should paste a short bio here manually if he wants the bot to use it.

**From public search ("Angus Hally HeyLina founder", 2026-05-24):**

- Angus's primary LinkedIn profile appears to be [linkedin.com/in/angus-hally-9ab66a87](https://www.linkedin.com/in/angus-hally-9ab66a87/), with the headline "Angus Hally - HeyLina".
- HeyLina maintains a LinkedIn company page at [linkedin.com/company/heylina](https://www.linkedin.com/company/heylina).
- A LinkedIn post from Angus (URL activity ID \`7301283711998676993\`) carries the hashtags \`#ai #transportinnovation #dataforgood #anmut\`, suggesting prior work at Anmut on data-for-good / transport themes.
- Another post (\`7300533726348783616\`) uses \`#dataproducts #dataaiproducts\`.

No interviews, press, or conference-talk pages surfaced in the search. Anything beyond the above should be added by Angus directly rather than inferred.`,
  },
] as const satisfies readonly KnowledgeEntry[];

/**
 * Map from route → entry, for the page-aware system prompt. Only entries
 * whose source is a route (starts with `/`) appear here.
 */
export const KNOWLEDGE_BY_ROUTE: Readonly<Record<string, KnowledgeEntry>> = {
  "/about": KNOWLEDGE_BUNDLE[0],
  "/cv": KNOWLEDGE_BUNDLE[1],
  "/": KNOWLEDGE_BUNDLE[3],
  "/projects": KNOWLEDGE_BUNDLE[4],
  "/contact": KNOWLEDGE_BUNDLE[5],
  "/projects/data-value-game": KNOWLEDGE_BUNDLE[7],
  "/projects/strava": KNOWLEDGE_BUNDLE[8],
  "/projects/timeline": KNOWLEDGE_BUNDLE[9],
  "/work-with-me": KNOWLEDGE_BUNDLE[11],
  "/blog": KNOWLEDGE_BUNDLE[12],
  "/projects/bookmarks": KNOWLEDGE_BUNDLE[13],
  "/projects/eat-safe-uk": KNOWLEDGE_BUNDLE[14],
  "/projects/habit": KNOWLEDGE_BUNDLE[15],
  "/projects/ai/instapaper": KNOWLEDGE_BUNDLE[16],
  "/projects/ai/text-analysis": KNOWLEDGE_BUNDLE[17],
};

export const KNOWLEDGE_TOKEN_COUNT = 4157 as const;
