// AUTO-GENERATED by scripts/build-chat-routes.mjs — DO NOT EDIT.
// Edit src/app pages or src/lib/chat/visibility.config.ts
// and re-run `npm run build` (or `node scripts/build-chat-routes.mjs`).
//
// Committed so reviewers see content diffs in PRs.
// See docs/chatbotv1/design.md §6.1.

export const ROUTE_ALLOWLIST = [
  "/",
  "/about",
  "/announcements",
  "/blog",
  "/contact",
  "/cv",
  "/projects",
  "/projects/ai/instapaper",
  "/projects/ai/text-analysis",
  "/projects/bookmarks",
  "/projects/data-value-game",
  "/projects/eat-safe-uk",
  "/projects/habit",
  "/projects/strava",
  "/projects/timeline",
  "/share",
  "/share/test",
  "/work-with-me",
  "/work-with-me/consulting",
  "/work-with-me/maths",
  "/work-with-me/webdev",
] as const satisfies readonly string[];

export type AllowedRoute = (typeof ROUTE_ALLOWLIST)[number];
